baseURL: "/"
title: "温故知新 BLOG"
theme: "hugo-primer"
publishDir: "docs"
languageCode: "zh"
hasCJKLanguage: true
pygmentsCodeFences: true
pygmentsUseClasses: true
params:
  useIcon: true

menu:
  main:
    - name: "RSS"
      url: "/index.xml"
      weight: 200
